FROM php:8.0.0-apache

WORKDIR /var/www/html/

RUN chown -R 777 /var/www/html/

RUN export DEBIAN_FRONTEND=noninteractive && \
apt-get update -yqq && \
apt-get install -y nano && \
apt-get install -y curl && \
apt-get install -y apt-utils zip unzip && \
apt-get install -y libzip-dev libpq-dev && \
docker-php-ext-install pdo_mysql && \
docker-php-ext-install mysqli && \
docker-php-ext-configure zip && \
docker-php-ext-install zip && \
apt-get install -y sendmail libpng-dev && \
apt-get install -y zlib1g-dev 

# Image Handling PHP Extension --> 
RUN apt-get update && apt-get install -y libmagickwand-dev --no-install-recommends && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/src/php/ext/imagick; \
    curl -fsSL https://github.com/Imagick/imagick/archive/06116aa24b76edaf6b1693198f79e6c295eda8a9.tar.gz | tar xvz -C "/usr/src/php/ext/imagick" --strip 1; \
    docker-php-ext-install imagick;

RUN apt-get update && \
apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev && \
docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ && \
docker-php-ext-install gd

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

RUN composer global require laravel/installer \
&& export PATH="~/.composer/vendor/bin:$PATH" \
&& echo 'PATH="~/.composer/vendor/bin:$PATH"' >> ~/.bashrc \
&& /bin/bash -c 'source ~/.bashrc'

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
&& apt-get update && apt-get install -y nodejs

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
